### ISSUE TITLE
Argument 2 (JS::NativeWebSocketModule::SpecConnectOptions) of WebSocketModule.connect must not be null  

### ISSUE THREAD

**Issue by BridgeEast** [React-Sextant/react-native-reconnecting-websocket#1]
new WebSocket('ws://....');
直接这样使用，在安卓上没有问题，在iOS上频繁遇到报错
Argument 2 (JS::NativeWebSocketModule::SpecConnectOptions) of WebSocketModule.connect must not be null  RCTLogArgumentError(RCTModuleMethod*, unsigned long, objc_object*, char const*)     RCTModuleMethod.mm:67 __41-[RCTModuleMethod processMethodSignature]_block_invoke.164 -[RCTModuleMethod invokeWithBridge:module:arguments:] facebook::react::invokeInner(RCTBridge*, RCTModuleData*, unsigned int, folly::dynamic const&) facebook::react::RCTNativeModule::invoke(unsigned int, folly::dynamic&&, int)::$_0::operator()() const invocation function for block in facebook::react::RCTNativeModule::invoke(unsigned int, folly::dynamic&&, int) _dispatch_call_block_and_release _dispatch_client_callout _dispatch_main_queue_callback_4CF __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ __CFRunLoopRun CFRunLoopRunSpecific GSEventRunModal -[UIApplication _run] UIApplicationMain main start 0x0

**Comment by 1uokun** [comment]
Thanks for your PR👏
