### ISSUE TITLE
你要不要看看你写的文档，都写的什么？

### ISSUE THREAD

**Issue by wulaizi** [React-Sextant/react-native-reconnecting-websocket#5]

**Comment by 1uokun** [comment]
是哪里有问题呢

**Comment by wulaizi** [comment]
根本看不懂咋使用


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "React-Sextant/react-native-reconnecting-websocket"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月4日(星期一) 下午2:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [React-Sextant/react-native-reconnecting-websocket] 你要不要看看你写的文档，都写的什么？ (Issue #5)





 
是哪里有问题呢

**Comment by 1uokun** [comment]
文档已更新，默认需要有https://developer.mozilla.org/en-US/docs/Web/API/WebSocket 基础知识
